Table efficientcyCurve(tech,dir,step)                                                        
*PARAMETER NAME                            EFFICIENCYCURVE                                   
*INDICIES                                  Tech            Dir   Step                        
*TYPE                                      ROW             ROW   COLUMN                      
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                           Step1 Step2  Step3 Step4          
Electrolysis                          .    Import          0     0.08   0.2   1              
Electrolysis                          .    Export          0     0.27   0.35  0.3            
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
