SET Flowset(area,area,energy)                            
/                                                        
DK1                           .    Skive .    Wind       
DK1                           .    Skive .    Solar      
DK1                           .    Skive .    Electricity
DK1                           .    Skive .    CO2        
DK1                           .    Skive .    Water      
Skive                         .    DK1   .    Electricity
Skive                         .    DK1   .    Heat       
Skive                         .    DK1   .    HydrogenCom
Skive                         .    DK1   .    Methanol   
Skive                         .    DK1   .    Ammonia    
Skive                         .    DK1   .    Oxygen     
Skive                         .    DK1   .    Water      
Skive                         .    DK1   .    Steam      
Skive                         .    DK1   .    Nitrogen   
                                                         
                                                         
                                                         
                                                         
                                                         
/;                                                       
