SET FutureTech(tech)
/                   
AmmoniaSynthesis    
AirSeparationUnit   
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
/;                  
