SET Location(area,tech)                       
/                                             
Skive                   .    WindTurbine      
Skive                   .    SolarPV          
Skive                   .    Electrolysis     
Skive                   .    AmmoniaSynthesis 
Skive                   .    MethanolSynthesis
Skive                   .    HydrogenStorage  
Skive                   .    ElectricStorage  
Skive                   .    AirSeparationUnit
                                              
                                              
                                              
                                              
                                              
                                              
                                              
                                              
/;                                            
                                              
                                              
