Table Techdata(tech,dataset)                                                                                                                     
*PARAMETER NAME              TECHDATA                                                                                                            
*INDICIES                    Tech     Dataset                                                                                                    
*TYPE                        ROW      COLUMN                                                                                                     
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
*                            %of X/h  X/h      %load/h  %x         %x           x hours    x hours       euro/ x                                 
                             Minimum  Capacity RampRate CapacityUP CapacityDown StorageCap InitialVolume VariableOmcost StartupCost              
WindTurbine                           54.6                                                               0                                       
SolarPV                               27                                                                 0                                       
Electrolysis                 0.2      0.235    0.9      0.1        0.1                                   0              0                        
MethanolSynthesis                     1.9845                                                             35             0                        
AmmoniaSynthesis             0.2499   0.833    0.2                                                       0.1                                     
AirSeparationUnit                     1                                                                  0                                       
HydrogenStorage                       7                 0.1        0.1          7          3.5           0.05                                    
ElectricStorage                       1.6                                       1.6        1             0.08                                    
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
                                                                                                                                                 
